### ISSUE TITLE
403 Forbidden error when connecting from local to remote WP

### ISSUE THREAD

**Issue by manikmagar** [Afrozaar/wp-api-v2-client-java#13]
I develop my web application in local laptop and my wordpress is deployed on remote VPS. I use this API to get custom post data from wordpress. All was working good in local but suddenly I started getting 403 Forbidden error for every API call eg. getUsers(). 

There is no change in user/password/roles. API calls using postman with same user/password works. More surprisingly when I build the WAR from local and deployed on the VPS that hosts wordpress then there everything seems to work normally. I even created another simple maven java project in local, added this wp-api-v2-client-java dependency. Then created a simple JUnit test to getUsers() but it failed.

Also if I use Postman with same id/password to call same endpoint from my local to remote VPS, it works.

I am not sure what is going on. I have wp api beta 13 with wordpress 4.5, can that be an issue? I updated wp api to beta 13 as soon as it was out, I guessed it was working after that too.

**Comment by johanmynhardt** [comment]
Hi @manikmagar, yes, if you are using the beta12 jar the possibility is there that it will fail on some endpoints when you update the API.

Is it a no-go to build the latest jar from develop branch?

**Comment by manikmagar** [comment]
Hi @johanmynhardt , I will try building from develop branch but like I am only getting 403 error when I deploy my war in local tomcat/run in eclipse. Same WAR works properly on my VPS where I have tomcat and wordpress installed. I might try few more things today to see what might be the cause.

**Comment by johanmynhardt** [comment]
Hi @manikmagar, did you manage to figure out the issue you had here?

**Comment by manikmagar** [comment]
Hi @johanmynhardt, unfortunately I had to stop that project. I don't think I had progressed on this issue, sorry.

**Comment by johanmynhardt** [comment]
@manikmagar OK, thank you for your participation :)

I'm going to close this as I suspect it has to do with an environment configuration that is not related enough to the client.

Kind regards
