### ISSUE TITLE
Certificate error when https enabled wordpress is called.

### ISSUE THREAD

**Issue by manikmagar** [Afrozaar/wp-api-v2-client-java#17]
I was trying to get list of posts from https enabled wordpress but RestTemplate threw an exception for invalid certificate. I looked into the code but did not see any support for https. 

I have forked and modified Wordpress initialization process to optionally provide `ClientHttpRequestFactory` that handles TLS connections and now can call HTTPS endpoints too.

Is there any other way to handle SSL with current code?

**Comment by johanmynhardt** [comment]
Hi Manik,

Which JDK are you using? AFAIK there are differences between OpenJDK and OracleJDK builds - OpenJDK might not have this issue.

That said, if you create a pull request for the change you made in terms of `ClientHttpRequestFactory`, I can check it out and merge :)

**Comment by manikmagar** [comment]
Hi Johan, 

I use OracleJDK.

I think allowing to configure the http factory will give a flexible control over connection for consumers. I will submit the PR tonight. Check it out. 

Thanks :).
