### ISSUE TITLE
ClientConfig can not populate ClientHttpRequestFactory through YAML

### ISSUE THREAD

**Issue by johanmynhardt** [Afrozaar/wp-api-v2-client-java#19]
A better place for `requestFactory` would be outside of ClientConfig.

ClientConfig can be hydrated from a `.yaml` configuration, which currently
only supports deserialising POJO's.

Adding a builder to `ClientFactory` would be a better approach for 'advanced'
setup.

**Comment by johanmynhardt** [comment]
Hi @manikmagar,

I made a change in the way the client is built, but I guess the main difference for you would be the following (to use the builder):

```
-               final Wordpress client = ClientFactory.fromConfig(ClientConfig.of(httpsBaseURL, username, password, debug, requestFactory));
+               final Wordpress client = ClientFactory.builder(ClientConfig.of(httpBaseURL, username, password, debug))
+                .withRequestFactory(requestFactory)
+                .build();
```

**Comment by manikmagar** [comment]
Hi @johanmynhardt,

This may look like not so simple initialization of client as you need to chain multiple components to create client (the first code to step in this library), but that may be just me :), otherwise this works too.

Thanks for merging requestfactory change :+1:
