### ISSUE TITLE
Be able to parse rest exceptions from multisites.

### ISSUE THREAD

**Issue by johanmynhardt** [Afrozaar/wp-api-v2-client-java#29]
@MaSeKind discovered that there is a difference between 4.7.2 and versions before it:

OLD:
```
{
 "code": "user_email",
 "message": "Sorry, that email address is already used!",
 "data": null
}
```

NEW:
```
{
 "code": "rest_invalid_param",
 "message": "Invalid user parameter(s).",
 "data": {
   "status": 400
 },
 "additional_errors": [
   {
     "code": "user_name",
     "message": "Sorry, that username already exists!",
     "data": null
   },
   {
     "code": "user_email",
     "message": "Sorry, that email address is already used!",
     "data": null
   }
 ]
}
```

However, I could only pin it down to multisite-related changes from https://core.trac.wordpress.org/changeset/39219

**Comment by MaSeKind** [comment]
The error codes when creating users are different for multisites and single sites.
Single sites return the following error codes messages instead:

`existing_user_login` : when username exists on site
`existing_user_email` : when email address exists on site
