### ISSUE TITLE
Allow specifying request context (view | edit | embed) when requesting Media

### ISSUE THREAD

**Issue by fbunget** [Afrozaar/wp-api-v2-client-java#45]
The methods getMedia(Long id) and getPostMedias(Long postId) (from Medias) use request context mode EDIT.
Please allow specifying the context mode for both methods. (e.g. if I just want to fetch a Media for an ID, the usage of context=edit in getMedia(id) will cause the request to fail, because the Wordpress server only allows context=view).

**Comment by johanmynhardt** [comment]
Hi @fbunget,

Thank you for your request. I will have a look at this and add it as requested.

Kind regards,
Johan

**Comment by fbunget** [comment]
Hi @johanmynhardt,

Thank you for the update!

(currently I only need the `source_url` field from the media, so I can display it in a custom layout)

Kind regards,
Florin

**Comment by johanmynhardt** [comment]
OK, I'm having issues with Sonatype, it's extremely slow today. Once released It will become available on Maven Central in a while:

```xml
<dependency>
    <groupId>com.afrozaar.wordpress</groupId>
    <artifactId>wp-api-v2-client-java</artifactId>
    <version>4.8.3</version>
</dependency>
```
