### ISSUE TITLE
Any existed api for wpClient.getAllPosts()?

### ISSUE THREAD

**Issue by yangboz** [Afrozaar/wp-api-v2-client-java#50]
Any existed api for WordPress client to get all posts?

Thanks.

**Comment by clintonbosch** [comment]
final Builder<Post> searchBuilder = aSearchRequest(Post.class);
final SearchRequest<Post> searchRequest = searchBuilder.withOrderBy("date").withOrderAsc().build();
PagedResponse<Post> postsPagedResponse = wpClient.search(searchRequest);

**Comment by yangboz** [comment]
final SearchRequest.Builder<Post> searchBuilder = SearchRequest.Builder.aSearchRequest(Post.class);
final SearchRequest searchRequest = searchBuilder.withOrderBy("date").withOrderAsc().build();
PagedResponse postsPagedResponse = this.getWpClient(debug).search(searchRequest);
