### ISSUE TITLE
Can not create ParsedRestException

### ISSUE THREAD

**Issue by hasanli-orkhan** [Afrozaar/wp-api-v2-client-java#52]
Hello)
I am trying to write a first application in Spring to publish articles on the Wordpress website. I get an exception. I use WP REST API Client 4.8.3 and WordPress version 4.9.8 (clean installation). Where am I mistaken or not support this WordPress version? Thanks in advance!

```
public class WpTest {
    public static void main(String[] args) {

        String baseUrl = "http://example.com";
        String username = "customUser";
        String password = "customPassword";
        boolean usePermalinkEndpoint = false;
        boolean debug = true;

        final Wordpress client = ClientFactory.fromConfig(ClientConfig.of(baseUrl, username, password, usePermalinkEndpoint, debug));

        String expectedTitle = "Demo Title";
        String expectedExcerpt = "Demo Excerpt";
        String expectedContent = "Demo Content";

        final Post post = PostBuilder.aPost()
                .withTitle(TitleBuilder.aTitle().withRendered(expectedTitle).build())
                .build();

        try {
            final Post createdPost = client.createPost(post, PostStatus.publish);
        } catch (PostCreateException e) {
            e.printStackTrace();
        } 
    }
}
```
Exception:

> Exception in thread "main" java.lang.RuntimeException: Can not create ParsedRestException.
> Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input at [Source: (byte[])""; line: 1, column: 0]

**Comment by clintonbosch** [comment]
Hi

A few question, firstly is there any reason why you are using an older version of the API, I see the latest stabilized version is 4.11.1?

Can you confirm that you wordpress installation is accessible through the rest API by doing a curl command with edit context similar to this:
`curl --user 'customUser:customPassword' "https://www.example.com/wp-json/wp/v2/posts?context=edit"`

Regards,
Clinton

**Comment by hasanli-orkhan** [comment]
Hello!
Thank you for responding.
First of all, let me thank you for this wonderful library.
I took the latest version available on mvnrepository 4.8.3 - 
https://mvnrepository.com/artifact/com.afrozaar.wordpress/wp-api-v2-client-java
Where I can get the newest version?
Thanks in advance!
Best Regards, Orkhan.

P.S. Also I see an error when executing a cURL command related to WordPress. May be I need to update htaccess file. I will check it too.

> {"code":"rest_forbidden_context","message":"Sorry, you are not allowed to edit posts in this post type.","data":{"status":401}}

**Comment by clintonbosch** [comment]
Hi

So seems to ekude to the fact that your user has not been correctly set up. Can you confirm that your username and password are correct, also the user will have to be an author at least.

I see we have not pushed to mvn resontly, I will try and do this next week, but in the meantime you can fork the repo from github if you want and build it yourself

Regards,
Clinton

**Comment by hasanli-orkhan** [comment]
Hi,
per my check I have an admin access to the Wordpress site and can access to the dashboard with login and password credentials. 

I have installed this plugin https://github.com/WP-API/Basic-Auth and checked one more time. And in this case it works.

In moment I use 4.8.3 version and will update later from mvnrepository.

Thank you so much for your support!

P.S.  a small mistake (customUser:customPassword without brackets)
`curl --user customUser:customPassword "https://www.example.com/wp-json/wp/v2/posts?context=edit"`
