### ISSUE TITLE
Implementing post meta crud

### ISSUE THREAD

**Issue by hasanli-orkhan** [Afrozaar/wp-api-v2-client-java#53]
Hello, dear developer!
I builded this github library (version 4.13.0) and added it to my project. Thank you so much for this library. Is there any code examples about using Post Meta CRUD & Media ? 

P.S. Also I haven't found the actual version of this library on maven repository:
https://mvnrepository.com/artifact/com.afrozaar.wordpress/wp-api-v2-client-java

Thanks in advance!
Regards, Orkhan

**Comment by clintonbosch** [comment]
Hi

The WP core does not support for API calls on metadata, that is still requires a plugin https://wordpress.org/plugins/rest-api-meta-endpoints/ I am sure this will be migrated into the core in time.

We have a separate API for this https://github.com/Afrozaar/wp-api-v2-client-java-meta-plugin

Regards,
Clinton
