### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by ghost** [Afrozaar/wp-api-v2-client-java#54]
The last commit has been a while? Do you guys still work on this repository?

**Comment by MartinKeprta** [comment]
Hi... I was trying to use this plugin but without success. Best way how to get running integration with WP is to create code of Your own.

**Comment by clintonbosch** [comment]
Hi

Yes, this repo is still maintained and used in a number of production environments. Were you not able to get any posts? Is the WP rest API exposed (pre V4.7 WP do not have rest API exposed)? You can test this by browsing to https://yourdomain/wp-json/wp/v2/posts

Regards,
Clinton

**Comment by hasanli-orkhan** [comment]
Hello!
I have already asked a similar question before.
The last actual version is 4.13.0 (Look pom.xml) and not 4.8.1 (wich shown in README.md) and not 4.8.3 (wich accessible in mvnrepository - [Link](https://mvnrepository.com/artifact/com.afrozaar.wordpress/wp-api-v2-client-java)). So you need build project jar from sources and use the latest version 4.13.0
My last question here - https://github.com/Afrozaar/wp-api-v2-client-java/issues/52

Dear developers, please update project on mvnrepository (link above). Thanks in advance))

**Comment by ghost** [comment]
Well, I tried the latest artifact and it seems to work, but only with password authentication which is suboptimal. But nonetheless still very good work from the devs.

**Comment by clintonbosch** [comment]
Hi, the API does work in anonymous mode, we use it a lot that way
