### ISSUE TITLE
Internal Server Error 500 status code when createUser with existing username is called

### ISSUE THREAD

**Issue by manikmagar** [Afrozaar/wp-api-v2-client-java#9]
When I call createUser() method with existing username then instead of getting user already exists error, I get 500 Internal Server error.

I tried calling WP API for endpoint using Postman tool for same user id and there I am getting proper error message response as - 
{
  "code": "existing_user_login",
  "message": "Sorry, that username already exists!",
  "data": null
}

Need to check more on this.

**Comment by johanmynhardt** [comment]
Hi @manikmagar, thank you for reporting this.

I have fixed this in #10 :)

**Comment by manikmagar** [comment]
Thanks @johanmynhardt, I shall test it later today. Is this released to maven?

**Comment by johanmynhardt** [comment]
@manikmagar negative. Putting out other fires at work so chances are that I won't get around to that right away.

**Comment by manikmagar** [comment]
Ok no rush, With current version I will wrap my createUser function with try/catch for java.lang.Exception (for now) and once you release this to maven, I will replace it with correct exception. Thanks.
